apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - victoria-metrics.yaml
  - adguard-home.yaml
  - commafeed.yaml
  - nextcloud.yaml
  - forgejo.yaml
  - flake-update-cronjob.yaml
  - jellyfin.yaml
  - vaultwarden.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: forgejo-theme-catppuccin
    namespace: forgejo-k8s
    files:
      - theme-catppuccin-mocha-peach.css
