apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - victoria-metrics.yaml
  - adguard-home.yaml
  - commafeed.yaml
  - nextcloud.yaml
  - forgejo.yaml
  - jellyfin.yaml
  - vaultwarden.yaml
