apiVersion: batch/v1
kind: CronJob
metadata:
  name: shark-renovate
  namespace: forgejo-k8s
spec:
  schedule: "0 6 * * 6"
  timeZone: Europe/Istanbul
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          nodeSelector:
            kubernetes.io/hostname: w2
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: renovate
              image: renovate/renovate:41.140.1@sha256:9c70b9ee7010e5428710c52c37d6385e6420a1385205bd7e7e2048dafc802404
              args:
                - valeninki/k8s
              env:
                - name: RENOVATE_PLATFORM
                  value: forgejo
                - name: RENOVATE_ENDPOINT
                  value: http://forgejo-http.forgejo-k8s.svc.cluster.local:3000/api/v1/
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: shark-renovate-token
                      key: token
                - name: RENOVATE_GITHUB_COM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: shark-github-token
                      key: token
                - name: RENOVATE_GIT_AUTHOR
                  value: Shark <shark@valentinus.dev>
                - name: RENOVATE_ONBOARDING
                  value: "false"
                - name: RENOVATE_PLATFORM_AUTOMERGE
                  value: "false"
                - name: RENOVATE_CACHE_DIR
                  value: /tmp/renovate/cache
                - name: RENOVATE_LOG_LEVEL
                  value: info
              resources:
                requests:
                  cpu: 250m
                  ephemeral-storage: 1Gi
                  memory: 512Mi
                limits:
                  cpu: "2"
                  ephemeral-storage: 4Gi
                  memory: 2Gi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
          volumes:
            - name: tmp
              emptyDir:
                sizeLimit: 4Gi
