apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-db
  namespace: forgejo-k8s
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: db-secret
  storage:
    size: 1Gi
