apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-valentinus.dev
  namespace: traefik
spec:
  secretName: wildcard-valentinus.dev-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "adguard-home-k8s,commafeed-k8s,forgejo-k8s,metrics-k8s,nextcloud-k8s,vaultwarden-k8s"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "adguard-home-k8s,commafeed-k8s,forgejo-k8s,metrics-k8s,nextcloud-k8s,vaultwarden-k8s"
  dnsNames:
    - valentinus.dev
    - '*.valentinus.dev'
  issuerRef:
    name: mainissuer
    kind: ClusterIssuer
