---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
spec:
  destination:
    namespace: forgejo-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: oci://code.forgejo.org/forgejo-helm/forgejo
    targetRevision: 16.*
    path: .
    helm:
      parameters:
        - name: gitea.config.APP_NAME
          value: "Forgejo: Valen's Private Git Instance."
        - name: gitea.admin.existingSecret
          value: forgejo-admin-secret
      values: |
        nodeSelector:
          kubernetes.io/hostname: w2
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        
        gitea:
          additionalConfigFromEnvs:
            - name: FORGEJO__DATABASE__DB_TYPE
              value: postgres
            - name: FORGEJO__DATABASE__HOST
              value: forgejo-db-rw.forgejo-k8s.svc.cluster.local:5432
            - name: FORGEJO__DATABASE__NAME
              value: forgejo
            - name: FORGEJO__DATABASE__USER
              value: forgejo
            - name: FORGEJO__DATABASE__PASSWD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            
            - name: FORGEJO__SERVER__ROOT_URL
              value: https://git.valentinus.dev
            - name: FORGEJO__SERVER__DOMAIN
              value: git.valentinus.dev
            - name: FORGEJO__SECURITY__GLOBAL_TWO_FACTOR_REQUIREMENT
              value: all
            - name: FORGEJO__SERVER__SSH_DOMAIN
              value: git.valentinus.dev
        
          config:
            repository:
              ROOT: "/data/git/gitea-repositories"
            repository.pull-request:
              WORK_IN_PROGRESS_PREFIXES: "WIP:,[WIP]:"
            indexer:
              ISSUE_INDEXER_TYPE: bleve
              REPO_INDEXER_ENABLED: true
          
        postgresql-ha:
          enabled: false
        valkey-cluster:
          enabled: false
        valkey:
          enabled: false
        postgresql:
          enabled: false
        
        persistence:
          enabled: true
          size: 10Gi
  sources: []
  syncPolicy:
    syncOptions:
      - CreateNamespace = true
