apiVersion: v1
kind: ServiceAccount
metadata:
  name: forgejo-runner-k8s
  namespace: forgejo-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forgejo-runner-k8s-role
  namespace: forgejo-k8s
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forgejo-runner-k8s-rb
  namespace: forgejo-k8s
subjects:
  - kind: ServiceAccount
    name: forgejo-runner-k8s
    namespace: forgejo-k8s
roleRef:
  kind: Role
  name: forgejo-runner-k8s-role
  apiGroup: rbac.authorization.k8s.io
