apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - victoria-metrics-grafana.yaml
  - adguard-home-header.yaml
  - adguard-home-main.yaml
  - commafeed.yaml
  - forgejo.yaml
  - forgejo-ssh-public-service.yaml
  - jellyfin.yaml
  - nextcloud-dav-redirect.yaml
  - nextcloud-hsts-header.yaml
  - nextcloud-req-buffer.yaml
  - nextcloud.yaml
  - vaultwarden.yaml
