apiVersion: v1
kind: Namespace
metadata:
  name: adguard-home-k8s
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: adguard-home-header
  namespace: adguard-home-k8s
spec:
  headers:
    customRequestHeaders:
      Host: adguard-home-main.adguard-home-k8s.svc.cluster.local:443
      X-Real-IP: localhost
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-home-main
  namespace: adguard-home-k8s
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dns.valentinus.dev`)
      middlewares:
        - name: adguard-home-header
      priority: 10
      services:
        - kind: Service
          name: adguard-home-main
          namespace: adguard-home-k8s
          passHostHeader: true
          port: web-ssl
          scheme: https
  tls:
    domains:
      - main: dns.valentinus.dev
    secretName: wildcard-valentinus.dev-tls
