apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-reflector.yaml
  - metallb-system.yaml
  - traefik.yaml
  - cnpg-system.yaml
  - kured.yaml
  - longhorn-system.yaml
  - metrics-k8s.yaml
  - adguard-home-k8s.yaml
  - commafeed-k8s.yaml
  - forgejo-k8s.yaml
  - nextcloud-k8s.yaml
  - vaultwarden-k8s.yaml
