apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: l2-namespaces
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  wait: true
  prune: false
  path: ./flux-system/layers/l2-namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
