---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  destination:
    namespace: nextcloud-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jellyfin
    helm:
      parameters:
      - name: persistence.config.enabled
        value: "true"
      - name: persistence.config.accessMode
        value: ReadWriteOnce
      - name: persistence.config.size
        value: 3Gi
      - name: persistence.media.enabled
        value: "true"
      - name: persistence.media.existingClaim
        value: "nextcloud-nextcloud"
      - name: persistence.media.mountPath
        value: "/mnt/Music"
      - name: persistence.media.subPath
        value: "/data/valentinus/files/Music"
      - name: persistence.media.readOnly
        value: "true"
      values: |
        nodeSelector:
          kubernetes.io/hostname: w1
    repoURL: https://jellyfin.github.io/jellyfin-helm
    targetRevision: '2.*'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
