---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-cd
    helm:
      values: |-
        configs:
          params:
            server.insecure: true
        global:
          domain: argo.valentinus.dev
        nodeSelector:
          kubernetes.io/hostname: m1
        server:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        repoServer:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
        controller:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
        redis:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.*
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
