---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commafeed
  namespace: argocd
spec:
  destination:
    namespace: commafeed-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: commafeed
    helm:
      parameters:
      - name: main.options.publicUrl
        value: rss.valentinus.dev
      - name: postgresql.secret.autoCreate
        value: kustomize
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
