---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  destination:
    namespace: metrics-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: victoria-metrics-k8s-stack
    helm:
      values: |-
        grafana:
          plugins: []
          persistence:
            enabled: true
            size: 1Gi
          admin:
            existingSecret: vm-grafana
            userKey: admin-user
            passwordKey: admin-pass
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 1Gi

        vmsingle:
          enabled: true
          spec:
            retentionPeriod: "14"
            storage:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi

        vmagent:
          enabled: true
          spec:
            scrapeInterval: 60s
            selectAllByDefault: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 300m
                memory: 256Mi

        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false

        kube-state-metrics:
          enabled: true

        node-exporter:
          enabled: true

        defaultRules:
          rules:
            kubernetes: true
            node: true
            vmagent: true
            vmsingle: true
            vmhealth: true
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: 0.*
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
